The ASCII Project: src/graphics/SDL_Resize.h File Reference
SDL_Resize.h File Reference
#include <SDL.h>
Functions
SDL_Surface * SDL_Resize (SDL_Surface *src, float scale_factor, bool free_src=true, int filter=4)
SDL_Surface * SDL_Resize (SDL_Surface *src, int new_w, int new_h, bool free_src=true, int filter=4)
Function Documentation
SDL_Surface* SDL_Resize (SDL_Surface * src, float scale_factor, bool free_src = true, int filter = 4)
Definition at line 207 of file SDL_Resize.cpp.
References SDL_Resize().
Referenced by SDL_Resize().
{
    if (factor > 100.0f) factor = 100.0f; //let's be reasonable...
    int new_w = (int)(src->w * factor),
        new_h = (int)(src->h * factor);
    if (new_w < 1) new_w = 1;
    if (new_h < 1) new_h = 1;
    return SDL_Resize(src, new_w, new_h, free, filter);
}
SDL_Surface* SDL_Resize (SDL_Surface * src, int new_w, int new_h, bool free_src = true, int filter = 4)
Definition at line 218 of file SDL_Resize.cpp.
References has_alpha(), and Resample().
{
    SDL_Surface * dst;
    bool is_alpha = has_alpha(src);
    if (src->w == new_w && src->h == new_h)
    {
        //No change in size. Return an optimized image.
        if (is_alpha)
        {
            dst = SDL_DisplayFormatAlpha(src);
            SDL_SetAlpha(src, SDL_SRCALPHA, 0);
        }
        else
            dst = SDL_DisplayFormat(src);
        if (free)
            SDL_FreeSurface(src);
        return dst;
    }
    Uint32 rmask = 0x000000ff,
        gmask = 0x0000ff00,
        bmask = 0x00ff0000,
        amask = 0xff000000;
    #if SDL_BYTEORDER == SDL_BIG_ENDIAN
        rmask = 0xff000000;
        gmask = 0x00ff0000;
        bmask = 0x0000ff00;
        amask = 0x000000ff;
    #endif
    dst = SDL_CreateRGBSurface(0, new_w, new_h, 32, rmask, gmask, bmask, amask);
    SDL_Surface * temp = SDL_ConvertSurface(src,dst->format,0);
    if (free)
        SDL_FreeSurface(src);
    src = temp;
    Resample(src,dst,filter);
    SDL_FreeSurface(temp);
    if (is_alpha)
        {
            temp = SDL_DisplayFormatAlpha(dst);
            SDL_SetAlpha(temp, SDL_SRCALPHA, 0);
        }
        else
            temp = SDL_DisplayFormat(dst);
    SDL_FreeSurface(dst);
    return temp;
}