The ASCII Project: Mixer Class Reference
Mixer Class Reference
#include <Mixer.h>
Public Member Functions
Mixer ()
virtual ~Mixer ()
bool Load_Music (char *file)
void Unload_Music ()
bool Play_Music ()
void Pause_Music ()
void Stop_Music ()
bool Fade_In_Music (int ms, int loops=-1)
bool Load_Effect (char *file)
bool Play_Effect (int channel=-1, int loops=0)
void Global_Volume (int volume, int channel=-1)
void Music_Volume (int volume)
void Effect_Volume (int volume, int channel=-1)
Private Attributes
Mix_Music * music
Mix_Chunk * effect
Detailed Description
Definition at line 14 of file Mixer.h.
Constructor & Destructor Documentation
Mixer::Mixer ()
Definition at line 15 of file Mixer.cpp.
References effect, and music.
            {
  music = nullptr;
  effect = nullptr;
  Mix_OpenAudio( 22050, MIX_DEFAULT_FORMAT, 2, 4096 );
  int flags = MIX_INIT_OGG|MIX_INIT_MOD|MIX_INIT_MP3;
  Mix_Init(flags);
}
Mixer::~Mixer () virtual
Definition at line 28 of file Mixer.cpp.
References effect, and music.
             {
  // Stop_Music();
  if( music != nullptr )
    Mix_FreeMusic( music );
  if( effect != nullptr )
    Mix_FreeChunk( effect );
  Mix_CloseAudio();
  while(Mix_Init(0))
    Mix_Quit();
}
Member Function Documentation
void Mixer::Effect_Volume (int volume, int channel = -1)
Definition at line 170 of file Mixer.cpp.
{
}
bool Mixer::Fade_In_Music (int ms, int loops = -1)
Definition at line 105 of file Mixer.cpp.
References music.
Referenced by main().
{
  if( music != nullptr){
    if(Mix_FadeInMusic(music, loops, ms) == -1) {
      // well, there's no music, but most games don't break without music...
      printf("Mix_FadeInMusic: %s\n", Mix_GetError());
      return false;
    }
    else
      return true;
  }
  else
    return false;
}
void Mixer::Global_Volume (int volume, int channel = -1)
Definition at line 155 of file Mixer.cpp.
{
  Mix_Volume( channel, volume );
}
bool Mixer::Load_Effect (char * file)
Definition at line 123 of file Mixer.cpp.
References effect.
{
  if( effect != nullptr ){
    Mix_FreeChunk( effect );
  }
  effect = Mix_LoadWAV( file );
  if( effect == NULL )
    return false;
  else
    return true;
}
bool Mixer::Load_Music (char * file)
Definition at line 46 of file Mixer.cpp.
References music, and Unload_Music().
Referenced by main().
{
  Unload_Music();
  music = Mix_LoadMUS( file );
  if( music == NULL )
    return false;
  else
    return true;
}
void Mixer::Music_Volume (int volume)
Definition at line 163 of file Mixer.cpp.
Referenced by main().
{
  Mix_VolumeMusic( volume );
}
void Mixer::Pause_Music ()
Definition at line 88 of file Mixer.cpp.
                       {
  if( Mix_PausedMusic() == 1 )
    Mix_ResumeMusic();
  else
    Mix_PauseMusic();
}
bool Mixer::Play_Effect (int channel = -1, int loops = 0)
Definition at line 139 of file Mixer.cpp.
References effect.
{
  if( effect != nullptr){
    if( Mix_PlayChannel( channel, effect, loops) == -1 ){
      return false;
    }
    else
      return true;
  }
  else
    return false;
}
bool Mixer::Play_Music ()
Definition at line 69 of file Mixer.cpp.
References music.
                      {
  if( music != nullptr){
    if( Mix_PlayingMusic() == 0 ){
      if( Mix_PlayMusic( music, -1 ) == -1 ){
        return false;
      }
      else
        return true;
    }
    else
      return false;
  }
  else
    return false;
}
void Mixer::Stop_Music ()
Definition at line 98 of file Mixer.cpp.
Referenced by Unload_Music().
                      {
  Mix_HaltMusic();
}
void Mixer::Unload_Music ()
Definition at line 60 of file Mixer.cpp.
References music, and Stop_Music().
Referenced by Load_Music().
{
  if( music != nullptr ){
    Stop_Music();
    Mix_FreeMusic( music );
  }
}
Member Data Documentation
Mix_Chunk* Mixer::effect private
Definition at line 19 of file Mixer.h.
Referenced by Load_Effect(), Mixer(), Play_Effect(), and ~Mixer().
Mix_Music* Mixer::music private
Definition at line 18 of file Mixer.h.
Referenced by Fade_In_Music(), Load_Music(), Mixer(), Play_Music(), Unload_Music(), and ~Mixer().
The documentation for this class was generated from the following files:
src/audio/Mixer.h
src/audio/Mixer.cpp