The ASCII Project: ClientWindow Class Reference
ClientWindow Class Reference
#include <ClientWindow.h>
Public Member Functions
ClientWindow ()
virtual ~ClientWindow ()
void Init ()
bool InitSDL ()
void ClientWindowUpdate (SDL_Surface *source, SDL_Surface *destination)
Public Attributes
BitmapFont * fontHandler
Window * mainWindow
SDL_Surface * mainScreen
Private Attributes
SDL_Surface * fontFile
Detailed Description
Definition at line 16 of file ClientWindow.h.
Constructor & Destructor Documentation
ClientWindow::ClientWindow ()
Definition at line 18 of file ClientWindow.cpp.
References Init().
{
  Init();
}
ClientWindow::~ClientWindow () virtual
Definition at line 62 of file ClientWindow.cpp.
{
  SDL_Quit();
}
Member Function Documentation
void ClientWindow::ClientWindowUpdate (SDL_Surface * source, SDL_Surface * destination)
Definition at line 53 of file ClientWindow.cpp.
{
  SDL_BlitSurface(source, nullptr, destination, nullptr);
  SDL_Flip(destination);
}
void ClientWindow::Init ()
Definition at line 26 of file ClientWindow.cpp.
References fontFile, fontHandler, InitSDL(), mainScreen, mainWindow, and Window::screen.
Referenced by ClientWindow().
                       {
  // Start SDL Engine
  InitSDL();
  // Create our "global" resizable window
  mainWindow = new Window();
  mainScreen = mainWindow->screen;
  // Load up our font file and the Handler
  fontFile = IMG_Load( "data/font.png" );
  fontHandler = new BitmapFont( fontFile );
}
bool ClientWindow::InitSDL ()
Definition at line 42 of file ClientWindow.cpp.
Referenced by Init().
{
  if(SDL_Init( SDL_INIT_EVERYTHING ) == -1 ){
    return false;
  }
  return true;
}
Member Data Documentation
SDL_Surface* ClientWindow::fontFile private
Definition at line 20 of file ClientWindow.h.
Referenced by Init().
BitmapFont* ClientWindow::fontHandler
Definition at line 28 of file ClientWindow.h.
Referenced by Init(), and main().
SDL_Surface* ClientWindow::mainScreen
Definition at line 30 of file ClientWindow.h.
Referenced by Init(), and main().
Window* ClientWindow::mainWindow
Definition at line 29 of file ClientWindow.h.
Referenced by ClientKeyboard::Handle_Keys(), Init(), and main().
The documentation for this class was generated from the following files:
src/graphics/ClientWindow.h
src/graphics/ClientWindow.cpp