The ASCII Project: Window Class Reference
Window Class Reference
#include <Window.h>
Public Member Functions
Window ()
virtual ~Window ()
void Handle_Events (SDL_Event event)
void Toggle_Fullscreen ()
void Clear_Screen ()
void Add_To_FrameList (Frame *src)
void Draw_Frames ()
void Draw_Single_Frame (Frame *frame)
void Remove_Frame (Frame *remove)
void Focus_Frame (Frame *focus)
void Focus_Next_Frame ()
void Focus_Previous_Frame ()
void Add_To_Event_Queue (SDL_Event event)
bool Error ()
Public Attributes
SDL_Surface * screen
Private Attributes
bool windowed
bool windowOK
std::vector< Frame * > frameList
SDL_Event eventQueue
Detailed Description
Definition at line 19 of file Window.h.
Constructor & Destructor Documentation
Window::Window ()
Definition at line 22 of file Window.cpp.
References screen, SCREEN_BPP, SCREEN_HEIGHT, SCREEN_WIDTH, windowed, and windowOK.
              {
  // Set up the screen
  screen = SDL_SetVideoMode( SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_BPP, SDL_SWSURFACE | SDL_RESIZABLE );
  if( screen == NULL ){
    windowOK = false;
    return;
  }
  else{
    windowOK = true;
  }
  SDL_WM_SetCaption( "The ASCII Project - Client - 0.0.1f", NULL);
  windowed = true;
  //  eventQueue = nullptr;
}
virtual Window::~Window () inline virtual
Definition at line 35 of file Window.h.
{};
Member Function Documentation
void Window::Add_To_Event_Queue (SDL_Event event)
Definition at line 279 of file Window.cpp.
References eventQueue.
Referenced by ClientKeyboard::Handle_Keys().
{
  eventQueue = event;
}
void Window::Add_To_FrameList (Frame * src)
Definition at line 179 of file Window.cpp.
References frameList.
Referenced by main().
{
  frameList.push_back(src);
  frameList.back()->Set_FrameList_Index(frameList.size()-1);
}
void Window::Clear_Screen ()
Definition at line 80 of file Window.cpp.
References screen.
Referenced by main().
{
  uint32_t black = SDL_MapRGB( screen->format, 0, 0, 0);
  SDL_FillRect( screen, NULL, black);
}
void Window::Draw_Frames ()
Definition at line 187 of file Window.cpp.
References eventQueue, frameList, and screen.
Referenced by main().
{
  for( int i = 0; i < frameList.size(); i++){
    // This doesn't actually make the Frame process the event
    // It only tells the Frame that it now has an Event to process
    if( frameList.at(i)->Check_Focus() ){
      //SDL_Event tmpEvent = *eventQueue;
      frameList.at(i)->Handle_Event( eventQueue );
      //      delete eventQueue;
    }
    frameList.at(i)->Render_Widgets();
    // If the frame wants us to draw it, we happily do so.
    if( frameList.at(i)->drawThisFrame ){
      SDL_Rect destination;
      destination.x = frameList.at(i)->posX;
      destination.y = frameList.at(i)->posY;
      destination.w = frameList.at(i)->width;
      destination.h = frameList.at(i)->height;
      SDL_BlitSurface( frameList.at(i)->sdlScreen, NULL, screen, &destination);
    }
    // If the removal flag has been set, then we
    // go ahead and delete the frame and break from the
    // Function here.
    if( frameList.at(i)->removeThisFrame ){
      frameList.erase(frameList.begin()+i);
      return;
    }
    // We force a fix on the FrameList index before moving the frame
    // around in the FrameList queue.
    if( frameList.at(i)->Get_FrameList_Index() != i ){
      frameList.at(i)->Set_FrameList_Index( i );
    }
    // We check if we need to drop this frame, if not then we validate
    // the index and if this frame is at the top of the
    if( (frameList.at(i)->Get_FrameList_Index() == (frameList.size() - 1)) && ( !frameList.at(i)->Check_Focus() ) ){
      // We move the frame to the end of the frameList vector and set
      // Focus to 'true' so that the frame in question gains Focus
      frameList.at(i)->Set_Focus( true );
      frameList.push_back(frameList.at(i));
      frameList.erase(frameList.begin()+i);
    }
    else if( (frameList.at(i)->Get_FrameList_Index() != (frameList.size() - 1)) && ( frameList.at(i)->Check_Focus() ) ){
      // We also disable focus this time around
      // During the next cycle, this will be reset to true if
      // this frame remains at the end of the queue
      // This follows a LIFO (last in - first out) methodology.
      frameList.at(i)->Set_Focus(false);
      // First we move the Frame to the beginning of the Queue
      // Remember this is "backwards" because of LIFO
      frameList.push_back(frameList.at(i));
      frameList.erase(frameList.begin()+i);
    }
      else if( frameList.at(i)->Get_FrameList_Index() != (frameList.size() -1) ){
        // This is a global reset of anything that should not be
        // In Focus
      frameList.at(i)->Set_Focus( false );
    }
  }
}
void Window::Draw_Single_Frame (Frame * frame)
bool Window::Error ()
Definition at line 272 of file Window.cpp.
References windowOK.
Referenced by main().
{
    return !windowOK;
}
void Window::Focus_Frame (Frame * focus)
void Window::Focus_Next_Frame ()
void Window::Focus_Previous_Frame ()
void Window::Handle_Events (SDL_Event event)
Definition at line 90 of file Window.cpp.
References screen, SCREEN_BPP, Toggle_Fullscreen(), and windowOK.
Referenced by main().
{
//If there's something wrong with the window
    if( windowOK == false )
    {
        return;
    }
    //If the window resized
    if( event.type == SDL_VIDEORESIZE )
    {
        //Resize the screen
        screen = SDL_SetVideoMode( event.resize.w, event.resize.h, SCREEN_BPP, SDL_SWSURFACE | SDL_RESIZABLE );
        //If there's an error
        if( screen == NULL )
        {
            windowOK = false;
            return;
        }
    }
 //If enter was pressed
    else if( ( event.type == SDL_KEYDOWN ) && ( event.key.keysym.sym == SDLK_RETURN ) && ( event.key.keysym.mod & KMOD_ALT ))
    {
        //Turn fullscreen on/off
        Toggle_Fullscreen();
    }
    /*
 //If the window focus changed
    else if( event.type == SDL_ACTIVEEVENT )
    {
        //If the window was iconified or restored
        if( event.active.state & SDL_APPACTIVE )
        {
            //If the application is no longer active
            if( event.active.gain == 0 )
            {
                SDL_WM_SetCaption( "Window Event Test: Iconified", NULL );
            }
            else
            {
                SDL_WM_SetCaption( "Window Event Test", NULL );
            }
        }
//If something happened to the keyboard focus
        else if( event.active.state & SDL_APPINPUTFOCUS )
        {
            //If the application lost keyboard focus
            if( event.active.gain == 0 )
            {
                SDL_WM_SetCaption( "Window Event Test: Keyboard focus lost", NULL );
            }
            else
            {
                SDL_WM_SetCaption( "Window Event Test", NULL );
            }
        }
        //If something happened to the mouse focus
        else if( event.active.state & SDL_APPMOUSEFOCUS )
        {
            //If the application lost mouse focus
            if( event.active.gain == 0 )
            {
                SDL_WM_SetCaption( "Window Event Test: Mouse Focus Lost", NULL );
            }
            else
            {
                SDL_WM_SetCaption( "Window Event Test", NULL );
            }
        }
        } */
//If the window's screen has been altered
    else if( event.type == SDL_VIDEOEXPOSE )
    {
        //Update the screen
        if( SDL_Flip( screen ) == -1 )
        {
            //If there's an error
            windowOK = false;
            return;
        }
    }
}
void Window::Remove_Frame (Frame * remove)
void Window::Toggle_Fullscreen ()
Definition at line 43 of file Window.cpp.
References screen, SCREEN_BPP, SCREEN_HEIGHT, SCREEN_WIDTH, windowed, and windowOK.
Referenced by Handle_Events().
{
  //If the screen is windowed
  if( windowed == true )
    {
      //Set the screen to fullscreen
      screen = SDL_SetVideoMode( SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_BPP, SDL_SWSURFACE | SDL_RESIZABLE | SDL_FULLSCREEN );
      //If there's an error
      if( screen == NULL )
        {
          windowOK = false;
          return;
        }
      //Set the window state flag
      windowed = false;
    }
  //If the screen is fullscreen
  else if( windowed == false )
    {
      //Window the screen
      screen = SDL_SetVideoMode( SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_BPP, SDL_SWSURFACE | SDL_RESIZABLE );
      //If there's an error
      if( screen == NULL )
        {
          windowOK = false;
          return;
        }
      //Set the window state flag
      windowed = true;
    }
}
Member Data Documentation
SDL_Event Window::eventQueue private
Definition at line 30 of file Window.h.
Referenced by Add_To_Event_Queue(), and Draw_Frames().
std::vector<Frame *> Window::frameList private
Definition at line 28 of file Window.h.
Referenced by Add_To_FrameList(), and Draw_Frames().
SDL_Surface* Window::screen
Definition at line 35 of file Window.h.
Referenced by Clear_Screen(), Draw_Frames(), Handle_Events(), ClientWindow::Init(), Toggle_Fullscreen(), and Window().
bool Window::windowed private
Definition at line 24 of file Window.h.
Referenced by Toggle_Fullscreen(), and Window().
bool Window::windowOK private
Definition at line 26 of file Window.h.
Referenced by Error(), Handle_Events(), Toggle_Fullscreen(), and Window().
The documentation for this class was generated from the following files:
src/graphics/Window.h
src/graphics/Window.cpp