The ASCII Project: BitmapFont Class Reference
BitmapFont Class Reference
#include <BitmapFont.h>
Public Member Functions
BitmapFont ()
BitmapFont (SDL_Surface *surface)
void Build_Font (SDL_Surface *surface)
void Show_Text (int x, int y, std::wstring source, SDL_Surface *surface)
void Show_Colored_Text (int x, int y, SDL_Color ForeColor, SDL_Color BackColor, std::wstring source, SDL_Surface *destination)
void Print_Colored_Character (wchar_t character, SDL_Color ForeColor, SDL_Color BackColor, int X, int Y, SDL_Surface *destination)
void Apply_Surface (int x, int y, SDL_Surface *source, SDL_Surface *destination, SDL_Rect *clip=NULL)
Private Attributes
SDL_Surface * bitmap
SDL_Rect * chars [65536]
int newLine
int space
uint32_t foreColor
uint32_t backColor
Detailed Description
Definition at line 22 of file BitmapFont.h.
Constructor & Destructor Documentation
BitmapFont::BitmapFont ()
Definition at line 22 of file BitmapFont.cpp.
References bitmap, newLine, and space.
                      {
     bitmap = nullptr;
     newLine = 0;
     space = 0;
}
BitmapFont::BitmapFont (SDL_Surface * surface)
Definition at line 31 of file BitmapFont.cpp.
References Build_Font().
{
     Build_Font( surface );
}
Member Function Documentation
void BitmapFont::Apply_Surface (int x, int y, SDL_Surface * source, SDL_Surface * destination, SDL_Rect * clip = NULL)
Definition at line 271 of file BitmapFont.cpp.
Referenced by Print_Colored_Character(), and Show_Text().
{
  SDL_Rect offset;
  offset.x = x;
  offset.y = y;
  if( SDL_BlitSurface( source, clip, destination, &offset) < 0 ){
    std::cout << "Apply Surface: Blit Error" << std::endl;
  }
}
void BitmapFont::Build_Font (SDL_Surface * surface)
Definition at line 38 of file BitmapFont.cpp.
References backColor, bitmap, chars, foreColor, pixels::Get_Pixel32(), newLine, and space.
Referenced by BitmapFont().
{
     if( surface == nullptr){
          return;
     }
     // Load our bitmap font
     bitmap = surface;
     uint32_t bgColor = SDL_MapRGB( bitmap->format, 0x00, 0x00, 0x00);
     backColor = pixels::Get_Pixel32( 0, 0, bitmap);
     foreColor = 0xFFFFFF;
     SDL_SetColorKey( bitmap, SDL_SRCCOLORKEY, SDL_MapRGB( bitmap->format, 0, 0, 0) );
     // Character Cell dimensions
     int cellW = bitmap->w / 32;
     int cellH = bitmap->h / 2048;
     // New Line Variables
     int top = cellH;
     int baseA = cellH;
     // The current chars[%] value we're setting
     int currentChar = 0;
     // Start by cell rows
     for( int rows = 0; rows < 2048; rows++){
       for( int cols = 0; cols < 32; cols++){
         chars[currentChar] = new SDL_Rect;
         // Start by setting our Character offsets
         chars[currentChar]->x = cellW * cols;
         chars[currentChar]->y = cellH * rows;
         // Set character dimensions
         chars[currentChar]->w = cellW;
         chars[currentChar]->h = cellH;
         // Go to next character
         currentChar++;
       }
     }
     // Calculate space
     space = cellW;
     newLine = cellH;
}
void BitmapFont::Print_Colored_Character (wchar_t character, SDL_Color ForeColor, SDL_Color BackColor, int X, int Y, SDL_Surface * destination)
Definition at line 205 of file BitmapFont.cpp.
References Apply_Surface(), backColor, bitmap, chars, pixels::Get_Pixel32(), and pixels::Put_Pixel32().
Referenced by main(), and Show_Colored_Text().
{
  int index = character;
  SDL_Surface *tmpSurface = SDL_CreateRGBSurface( SDL_SWSURFACE, chars[index]->w, chars[index]->h, bitmap->format->BitsPerPixel, bitmap->format->Rmask, bitmap->format->Gmask, bitmap->format->Bmask, 0);
  SDL_LockSurface( bitmap );
  SDL_LockSurface( tmpSurface );
  int changey = 0;
  int changex = 0;
  for ( int y = chars[index]->y; y < (chars[index]->h + chars[index]->y); ++y)
    {
      for ( int x = chars[index]->x; x < (chars[index]->w + chars[index]->x); ++x)
        {
          uint32_t copyPixel = pixels::Get_Pixel32( x, y, bitmap);
          pixels::Put_Pixel32( changex, changey, copyPixel, tmpSurface);
          changex++;
        }
      changex = 0;
      changey++;
    }
  // Afterwards, we color tmpSurface and apply it
  // To the screen at the requested x, y offsets
  uint32_t *pixels = (uint32_t *)tmpSurface->pixels;
  for(int i = 0; i < tmpSurface->w * tmpSurface->h; i++){
    if( pixels[i] !=  backColor ){
      pixels[i] = SDL_MapRGB( tmpSurface->format, ForeColor.r, ForeColor.g, ForeColor.b);
    }
    uint32_t newColor = SDL_MapRGB( tmpSurface->format, ForeColor.r, ForeColor.g, ForeColor.b);
    if( pixels[i] != newColor ){
      pixels[i] = SDL_MapRGB( tmpSurface->format, BackColor.r, BackColor.g, BackColor.b);
    }
  }
  SDL_UnlockSurface( bitmap );
  SDL_UnlockSurface( tmpSurface );
  SDL_Rect offset;
  offset.x = X;
  offset.y = Y;
  Apply_Surface( X, Y, tmpSurface, destination);
  SDL_FreeSurface( tmpSurface );
}
void BitmapFont::Show_Colored_Text (int x, int y, SDL_Color ForeColor, SDL_Color BackColor, std::wstring source, SDL_Surface * destination)
Definition at line 128 of file BitmapFont.cpp.
References bitmap, chars, newLine, and Print_Colored_Character().
Referenced by main().
{
  int X = x, Y = y;
  //If the font has been built
  if( bitmap != NULL )
    {
      //Go through the text
      for( int show = 0; show < source.length(); show++ )
        {
          //If the current character is a newline
          if( source[ show ] == '\n' )
            {
              //Move down
              Y += newLine;
              //Move back
              X = x - chars[0]->w;
            }
          else{
            //Show the character
            Print_Colored_Character( (wchar_t)source[ show ], ForeColor, BackColor, X, Y, destination);
          }
          //Move over the width of the character with one pixel of padding
          X += chars[ 0 ]->w;
        }
    }
}
void BitmapFont::Show_Text (int x, int y, std::wstring source, SDL_Surface * surface)
Definition at line 91 of file BitmapFont.cpp.
References Apply_Surface(), bitmap, chars, and newLine.
{
  int X = x, Y = y;
  //If the font has been built
  if( bitmap != NULL )
    {
      //Go through the text
      for( int show = 0; show < source.length(); show++ )
        {
          //If the current character is a newline
          if( source[ show ] == '\n' )
            {
              //Move down
              Y += newLine;
              //Move back
              X = x - chars[0]->w;
            }
          else{
          //Get the ASCII value of the character
          int ascii = (wchar_t)source[ show ];
          //Show the character
          Apply_Surface( X, Y, bitmap, surface, chars[ ascii ] );
          }
          //Move over the width of the character with one pixel of padding
          X += chars[ 0 ]->w;
        }
    }
}
Member Data Documentation
uint32_t BitmapFont::backColor private
Definition at line 35 of file BitmapFont.h.
Referenced by Build_Font(), and Print_Colored_Character().
SDL_Surface* BitmapFont::bitmap private
Definition at line 27 of file BitmapFont.h.
Referenced by BitmapFont(), Build_Font(), Print_Colored_Character(), Show_Colored_Text(), and Show_Text().
SDL_Rect* BitmapFont::chars[65536] private
Definition at line 29 of file BitmapFont.h.
Referenced by Build_Font(), Print_Colored_Character(), Show_Colored_Text(), and Show_Text().
uint32_t BitmapFont::foreColor private
Definition at line 35 of file BitmapFont.h.
Referenced by Build_Font().
int BitmapFont::newLine private
Definition at line 32 of file BitmapFont.h.
Referenced by BitmapFont(), Build_Font(), Show_Colored_Text(), and Show_Text().
int BitmapFont::space private
Definition at line 32 of file BitmapFont.h.
Referenced by BitmapFont(), and Build_Font().
The documentation for this class was generated from the following files:
src/graphics/BitmapFont.h
src/graphics/BitmapFont.cpp