#!/bin/sh

#  CleanServerdata.sh
#  The ASCII Project
#
#  Created by Jonathan Rumion on 12/24/13.
#  Copyright (c) 2013 The ASCII Project. All rights reserved.
#
#  This script is used for cleaning various pieces of data generated by the server.
#  Depending on the options used, it will clear map data, entity data and other pieces of static data.
#  If you're running this in production, be extremely careful not to remove character data you may otherwise need.
#  And as always, make sure you have adequete backups!
# 
#